# coding: utf-8

"""
    FDM API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.validation_api import ValidationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestValidationApi(unittest.TestCase):
    """ValidationApi unit test stubs"""

    def setUp(self):
        self.api = api.validation_api.ValidationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_validation_status_data_data_type_get(self):
        """Test case for v1_validation_status_data_data_type_get

        """
        pass

    def test_v1_validation_status_data_field_data_type_get(self):
        """Test case for v1_validation_status_data_field_data_type_get

        """
        pass

    def test_v1_validation_status_data_field_value_data_type_field_name_get(self):
        """Test case for v1_validation_status_data_field_value_data_type_field_name_get

        """
        pass

    def test_v1_validation_status_data_types_get(self):
        """Test case for v1_validation_status_data_types_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
