# coding: utf-8

"""
    FDM API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.curve_summary_api import CurveSummaryApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCurveSummaryApi(unittest.TestCase):
    """CurveSummaryApi unit test stubs"""

    def setUp(self):
        self.api = api.curve_summary_api.CurveSummaryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_curve_forecast_curve_id_forecast_date_get(self):
        """Test case for v1_curve_forecast_curve_id_forecast_date_get

        """
        pass

    def test_v1_curve_forecast_list_curve_id_get(self):
        """Test case for v1_curve_forecast_list_curve_id_get

        """
        pass

    def test_v1_curve_scenario_curve_id_get(self):
        """Test case for v1_curve_scenario_curve_id_get

        """
        pass

    def test_v1_curve_summary_forecasts_curve_id_get(self):
        """Test case for v1_curve_summary_forecasts_curve_id_get

        """
        pass

    def test_v1_curve_summary_values_curve_id_get(self):
        """Test case for v1_curve_summary_values_curve_id_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
