# coding: utf-8

"""
    FDM API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.fdmapidtov1_tabular_data_data_type_field import FDMAPIDTOV1TabularDataDataTypeField  # noqa: E501
from swagger_client.rest import ApiException


class TestFDMAPIDTOV1TabularDataDataTypeField(unittest.TestCase):
    """FDMAPIDTOV1TabularDataDataTypeField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFDMAPIDTOV1TabularDataDataTypeField(self):
        """Test FDMAPIDTOV1TabularDataDataTypeField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.fdmapidtov1_tabular_data_data_type_field.FDMAPIDTOV1TabularDataDataTypeField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
