# coding: utf-8

"""
    FDM API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.fdmapidtov1_crudes_crudes_refinery_meta import FDMAPIDTOV1CrudesCrudesRefineryMeta  # noqa: E501
from swagger_client.rest import ApiException


class TestFDMAPIDTOV1CrudesCrudesRefineryMeta(unittest.TestCase):
    """FDMAPIDTOV1CrudesCrudesRefineryMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFDMAPIDTOV1CrudesCrudesRefineryMeta(self):
        """Test FDMAPIDTOV1CrudesCrudesRefineryMeta"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.fdmapidtov1_crudes_crudes_refinery_meta.FDMAPIDTOV1CrudesCrudesRefineryMeta()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
