# coding: utf-8

"""
    FDM API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.refinery_units_and_turnarounds_api import RefineryUnitsAndTurnaroundsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRefineryUnitsAndTurnaroundsApi(unittest.TestCase):
    """RefineryUnitsAndTurnaroundsApi unit test stubs"""

    def setUp(self):
        self.api = api.refinery_units_and_turnarounds_api.RefineryUnitsAndTurnaroundsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_iir_ref_turnaround_daily_data_get(self):
        """Test case for v1_iir_ref_turnaround_daily_data_get

        """
        pass

    def test_v1_iir_ref_turnaround_data_get(self):
        """Test case for v1_iir_ref_turnaround_data_get

        """
        pass

    def test_v1_iir_ref_turnaround_field_get(self):
        """Test case for v1_iir_ref_turnaround_field_get

        """
        pass

    def test_v1_iir_ref_turnaround_field_value_field_name_get(self):
        """Test case for v1_iir_ref_turnaround_field_value_field_name_get

        """
        pass

    def test_v1_iir_ref_unit_data_get(self):
        """Test case for v1_iir_ref_unit_data_get

        """
        pass

    def test_v1_iir_ref_unit_field_get(self):
        """Test case for v1_iir_ref_unit_field_get

        """
        pass

    def test_v1_iir_ref_unit_field_value_field_name_get(self):
        """Test case for v1_iir_ref_unit_field_value_field_name_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
