# coding: utf-8

"""
    FDM API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.fdmapidtov1_curve_import import FDMAPIDTOV1CurveImport  # noqa: E501
from swagger_client.rest import ApiException


class TestFDMAPIDTOV1CurveImport(unittest.TestCase):
    """FDMAPIDTOV1CurveImport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFDMAPIDTOV1CurveImport(self):
        """Test FDMAPIDTOV1CurveImport"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.fdmapidtov1_curve_import.FDMAPIDTOV1CurveImport()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
