# coding: utf-8

"""
    FDM API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.fdmapidtov1_curve_forecast_scenario import FDMAPIDTOV1CurveForecastScenario  # noqa: E501
from swagger_client.rest import ApiException


class TestFDMAPIDTOV1CurveForecastScenario(unittest.TestCase):
    """FDMAPIDTOV1CurveForecastScenario unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFDMAPIDTOV1CurveForecastScenario(self):
        """Test FDMAPIDTOV1CurveForecastScenario"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.fdmapidtov1_curve_forecast_scenario.FDMAPIDTOV1CurveForecastScenario()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
