# coding: utf-8

"""
    FDM API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.reference_data_api import ReferenceDataApi  # noqa: E501
from swagger_client.rest import ApiException


class TestReferenceDataApi(unittest.TestCase):
    """ReferenceDataApi unit test stubs"""

    def setUp(self):
        self.api = api.reference_data_api.ReferenceDataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_period_types_get(self):
        """Test case for v1_period_types_get

        """
        pass

    def test_v1_timezones_get(self):
        """Test case for v1_timezones_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
