# coding: utf-8

"""
    FDM API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.fixtures_api import FixturesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFixturesApi(unittest.TestCase):
    """FixturesApi unit test stubs"""

    def setUp(self):
        self.api = api.fixtures_api.FixturesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_fixtures_fixture_data_fixture_type_get(self):
        """Test case for v1_fixtures_fixture_data_fixture_type_get

        """
        pass

    def test_v1_fixtures_fixture_field_fixture_type_get(self):
        """Test case for v1_fixtures_fixture_field_fixture_type_get

        """
        pass

    def test_v1_fixtures_fixture_field_value_fixture_type_field_name_get(self):
        """Test case for v1_fixtures_fixture_field_value_fixture_type_field_name_get

        """
        pass

    def test_v1_fixtures_fixture_types_get(self):
        """Test case for v1_fixtures_fixture_types_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
