# coding: utf-8

"""
    FDM API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.trade_flows_api import TradeFlowsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTradeFlowsApi(unittest.TestCase):
    """TradeFlowsApi unit test stubs"""

    def setUp(self):
        self.api = api.trade_flows_api.TradeFlowsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_flows_flow_data_flow_type_get(self):
        """Test case for v1_flows_flow_data_flow_type_get

        """
        pass

    def test_v1_flows_flow_field_flow_type_get(self):
        """Test case for v1_flows_flow_field_flow_type_get

        """
        pass

    def test_v1_flows_flow_field_value_flow_type_field_name_get(self):
        """Test case for v1_flows_flow_field_value_flow_type_field_name_get

        """
        pass

    def test_v1_flows_flow_types_get(self):
        """Test case for v1_flows_flow_types_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
