# coding: utf-8

"""
    FDM API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class FDMAPIDTOV1TabularDataDataTypeField(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'data_type': 'str',
        'field_name': 'str',
        'field_datatype': 'str',
        'field_order_id': 'int',
        'field_display_name': 'str'
    }

    attribute_map = {
        'data_type': 'dataType',
        'field_name': 'fieldName',
        'field_datatype': 'fieldDatatype',
        'field_order_id': 'fieldOrderID',
        'field_display_name': 'fieldDisplayName'
    }

    def __init__(self, data_type=None, field_name=None, field_datatype=None, field_order_id=None, field_display_name=None):  # noqa: E501
        """FDMAPIDTOV1TabularDataDataTypeField - a model defined in Swagger"""  # noqa: E501
        self._data_type = None
        self._field_name = None
        self._field_datatype = None
        self._field_order_id = None
        self._field_display_name = None
        self.discriminator = None
        if data_type is not None:
            self.data_type = data_type
        if field_name is not None:
            self.field_name = field_name
        if field_datatype is not None:
            self.field_datatype = field_datatype
        if field_order_id is not None:
            self.field_order_id = field_order_id
        if field_display_name is not None:
            self.field_display_name = field_display_name

    @property
    def data_type(self):
        """Gets the data_type of this FDMAPIDTOV1TabularDataDataTypeField.  # noqa: E501


        :return: The data_type of this FDMAPIDTOV1TabularDataDataTypeField.  # noqa: E501
        :rtype: str
        """
        return self._data_type

    @data_type.setter
    def data_type(self, data_type):
        """Sets the data_type of this FDMAPIDTOV1TabularDataDataTypeField.


        :param data_type: The data_type of this FDMAPIDTOV1TabularDataDataTypeField.  # noqa: E501
        :type: str
        """

        self._data_type = data_type

    @property
    def field_name(self):
        """Gets the field_name of this FDMAPIDTOV1TabularDataDataTypeField.  # noqa: E501


        :return: The field_name of this FDMAPIDTOV1TabularDataDataTypeField.  # noqa: E501
        :rtype: str
        """
        return self._field_name

    @field_name.setter
    def field_name(self, field_name):
        """Sets the field_name of this FDMAPIDTOV1TabularDataDataTypeField.


        :param field_name: The field_name of this FDMAPIDTOV1TabularDataDataTypeField.  # noqa: E501
        :type: str
        """

        self._field_name = field_name

    @property
    def field_datatype(self):
        """Gets the field_datatype of this FDMAPIDTOV1TabularDataDataTypeField.  # noqa: E501


        :return: The field_datatype of this FDMAPIDTOV1TabularDataDataTypeField.  # noqa: E501
        :rtype: str
        """
        return self._field_datatype

    @field_datatype.setter
    def field_datatype(self, field_datatype):
        """Sets the field_datatype of this FDMAPIDTOV1TabularDataDataTypeField.


        :param field_datatype: The field_datatype of this FDMAPIDTOV1TabularDataDataTypeField.  # noqa: E501
        :type: str
        """

        self._field_datatype = field_datatype

    @property
    def field_order_id(self):
        """Gets the field_order_id of this FDMAPIDTOV1TabularDataDataTypeField.  # noqa: E501


        :return: The field_order_id of this FDMAPIDTOV1TabularDataDataTypeField.  # noqa: E501
        :rtype: int
        """
        return self._field_order_id

    @field_order_id.setter
    def field_order_id(self, field_order_id):
        """Sets the field_order_id of this FDMAPIDTOV1TabularDataDataTypeField.


        :param field_order_id: The field_order_id of this FDMAPIDTOV1TabularDataDataTypeField.  # noqa: E501
        :type: int
        """

        self._field_order_id = field_order_id

    @property
    def field_display_name(self):
        """Gets the field_display_name of this FDMAPIDTOV1TabularDataDataTypeField.  # noqa: E501


        :return: The field_display_name of this FDMAPIDTOV1TabularDataDataTypeField.  # noqa: E501
        :rtype: str
        """
        return self._field_display_name

    @field_display_name.setter
    def field_display_name(self, field_display_name):
        """Sets the field_display_name of this FDMAPIDTOV1TabularDataDataTypeField.


        :param field_display_name: The field_display_name of this FDMAPIDTOV1TabularDataDataTypeField.  # noqa: E501
        :type: str
        """

        self._field_display_name = field_display_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FDMAPIDTOV1TabularDataDataTypeField, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FDMAPIDTOV1TabularDataDataTypeField):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
