# coding: utf-8

"""
    FDM API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class FDMAPIDTOV1CurveMetadata(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'curve_id': 'int',
        'tags': 'list[FDMAPIDTOV1CurveMetadataTag]'
    }

    attribute_map = {
        'curve_id': 'curveID',
        'tags': 'tags'
    }

    def __init__(self, curve_id=None, tags=None):  # noqa: E501
        """FDMAPIDTOV1CurveMetadata - a model defined in Swagger"""  # noqa: E501
        self._curve_id = None
        self._tags = None
        self.discriminator = None
        if curve_id is not None:
            self.curve_id = curve_id
        if tags is not None:
            self.tags = tags

    @property
    def curve_id(self):
        """Gets the curve_id of this FDMAPIDTOV1CurveMetadata.  # noqa: E501


        :return: The curve_id of this FDMAPIDTOV1CurveMetadata.  # noqa: E501
        :rtype: int
        """
        return self._curve_id

    @curve_id.setter
    def curve_id(self, curve_id):
        """Sets the curve_id of this FDMAPIDTOV1CurveMetadata.


        :param curve_id: The curve_id of this FDMAPIDTOV1CurveMetadata.  # noqa: E501
        :type: int
        """

        self._curve_id = curve_id

    @property
    def tags(self):
        """Gets the tags of this FDMAPIDTOV1CurveMetadata.  # noqa: E501


        :return: The tags of this FDMAPIDTOV1CurveMetadata.  # noqa: E501
        :rtype: list[FDMAPIDTOV1CurveMetadataTag]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this FDMAPIDTOV1CurveMetadata.


        :param tags: The tags of this FDMAPIDTOV1CurveMetadata.  # noqa: E501
        :type: list[FDMAPIDTOV1CurveMetadataTag]
        """

        self._tags = tags

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FDMAPIDTOV1CurveMetadata, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FDMAPIDTOV1CurveMetadata):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
