# coding: utf-8

"""
    FDM API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class FDMAPIDTOV1CrudesCrudesRefineryMeta(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'refinery_code': 'str',
        'refinery_name': 'str',
        'country': 'str',
        'source': 'str',
        'last_updated': 'datetime'
    }

    attribute_map = {
        'refinery_code': 'refineryCode',
        'refinery_name': 'refineryName',
        'country': 'country',
        'source': 'source',
        'last_updated': 'lastUpdated'
    }

    def __init__(self, refinery_code=None, refinery_name=None, country=None, source=None, last_updated=None):  # noqa: E501
        """FDMAPIDTOV1CrudesCrudesRefineryMeta - a model defined in Swagger"""  # noqa: E501
        self._refinery_code = None
        self._refinery_name = None
        self._country = None
        self._source = None
        self._last_updated = None
        self.discriminator = None
        if refinery_code is not None:
            self.refinery_code = refinery_code
        if refinery_name is not None:
            self.refinery_name = refinery_name
        if country is not None:
            self.country = country
        if source is not None:
            self.source = source
        if last_updated is not None:
            self.last_updated = last_updated

    @property
    def refinery_code(self):
        """Gets the refinery_code of this FDMAPIDTOV1CrudesCrudesRefineryMeta.  # noqa: E501


        :return: The refinery_code of this FDMAPIDTOV1CrudesCrudesRefineryMeta.  # noqa: E501
        :rtype: str
        """
        return self._refinery_code

    @refinery_code.setter
    def refinery_code(self, refinery_code):
        """Sets the refinery_code of this FDMAPIDTOV1CrudesCrudesRefineryMeta.


        :param refinery_code: The refinery_code of this FDMAPIDTOV1CrudesCrudesRefineryMeta.  # noqa: E501
        :type: str
        """

        self._refinery_code = refinery_code

    @property
    def refinery_name(self):
        """Gets the refinery_name of this FDMAPIDTOV1CrudesCrudesRefineryMeta.  # noqa: E501


        :return: The refinery_name of this FDMAPIDTOV1CrudesCrudesRefineryMeta.  # noqa: E501
        :rtype: str
        """
        return self._refinery_name

    @refinery_name.setter
    def refinery_name(self, refinery_name):
        """Sets the refinery_name of this FDMAPIDTOV1CrudesCrudesRefineryMeta.


        :param refinery_name: The refinery_name of this FDMAPIDTOV1CrudesCrudesRefineryMeta.  # noqa: E501
        :type: str
        """

        self._refinery_name = refinery_name

    @property
    def country(self):
        """Gets the country of this FDMAPIDTOV1CrudesCrudesRefineryMeta.  # noqa: E501


        :return: The country of this FDMAPIDTOV1CrudesCrudesRefineryMeta.  # noqa: E501
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this FDMAPIDTOV1CrudesCrudesRefineryMeta.


        :param country: The country of this FDMAPIDTOV1CrudesCrudesRefineryMeta.  # noqa: E501
        :type: str
        """

        self._country = country

    @property
    def source(self):
        """Gets the source of this FDMAPIDTOV1CrudesCrudesRefineryMeta.  # noqa: E501


        :return: The source of this FDMAPIDTOV1CrudesCrudesRefineryMeta.  # noqa: E501
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this FDMAPIDTOV1CrudesCrudesRefineryMeta.


        :param source: The source of this FDMAPIDTOV1CrudesCrudesRefineryMeta.  # noqa: E501
        :type: str
        """

        self._source = source

    @property
    def last_updated(self):
        """Gets the last_updated of this FDMAPIDTOV1CrudesCrudesRefineryMeta.  # noqa: E501


        :return: The last_updated of this FDMAPIDTOV1CrudesCrudesRefineryMeta.  # noqa: E501
        :rtype: datetime
        """
        return self._last_updated

    @last_updated.setter
    def last_updated(self, last_updated):
        """Sets the last_updated of this FDMAPIDTOV1CrudesCrudesRefineryMeta.


        :param last_updated: The last_updated of this FDMAPIDTOV1CrudesCrudesRefineryMeta.  # noqa: E501
        :type: datetime
        """

        self._last_updated = last_updated

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FDMAPIDTOV1CrudesCrudesRefineryMeta, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FDMAPIDTOV1CrudesCrudesRefineryMeta):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
