# coding: utf-8

"""
    FDM API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class FDMAPIDTOV1CurveValuesSummary(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'curve_id': 'int',
        'last_update_time': 'datetime',
        'min_value_date': 'datetime',
        'max_value_date': 'datetime'
    }

    attribute_map = {
        'curve_id': 'curveID',
        'last_update_time': 'lastUpdateTime',
        'min_value_date': 'minValueDate',
        'max_value_date': 'maxValueDate'
    }

    def __init__(self, curve_id=None, last_update_time=None, min_value_date=None, max_value_date=None):  # noqa: E501
        """FDMAPIDTOV1CurveValuesSummary - a model defined in Swagger"""  # noqa: E501
        self._curve_id = None
        self._last_update_time = None
        self._min_value_date = None
        self._max_value_date = None
        self.discriminator = None
        if curve_id is not None:
            self.curve_id = curve_id
        if last_update_time is not None:
            self.last_update_time = last_update_time
        if min_value_date is not None:
            self.min_value_date = min_value_date
        if max_value_date is not None:
            self.max_value_date = max_value_date

    @property
    def curve_id(self):
        """Gets the curve_id of this FDMAPIDTOV1CurveValuesSummary.  # noqa: E501


        :return: The curve_id of this FDMAPIDTOV1CurveValuesSummary.  # noqa: E501
        :rtype: int
        """
        return self._curve_id

    @curve_id.setter
    def curve_id(self, curve_id):
        """Sets the curve_id of this FDMAPIDTOV1CurveValuesSummary.


        :param curve_id: The curve_id of this FDMAPIDTOV1CurveValuesSummary.  # noqa: E501
        :type: int
        """

        self._curve_id = curve_id

    @property
    def last_update_time(self):
        """Gets the last_update_time of this FDMAPIDTOV1CurveValuesSummary.  # noqa: E501


        :return: The last_update_time of this FDMAPIDTOV1CurveValuesSummary.  # noqa: E501
        :rtype: datetime
        """
        return self._last_update_time

    @last_update_time.setter
    def last_update_time(self, last_update_time):
        """Sets the last_update_time of this FDMAPIDTOV1CurveValuesSummary.


        :param last_update_time: The last_update_time of this FDMAPIDTOV1CurveValuesSummary.  # noqa: E501
        :type: datetime
        """

        self._last_update_time = last_update_time

    @property
    def min_value_date(self):
        """Gets the min_value_date of this FDMAPIDTOV1CurveValuesSummary.  # noqa: E501


        :return: The min_value_date of this FDMAPIDTOV1CurveValuesSummary.  # noqa: E501
        :rtype: datetime
        """
        return self._min_value_date

    @min_value_date.setter
    def min_value_date(self, min_value_date):
        """Sets the min_value_date of this FDMAPIDTOV1CurveValuesSummary.


        :param min_value_date: The min_value_date of this FDMAPIDTOV1CurveValuesSummary.  # noqa: E501
        :type: datetime
        """

        self._min_value_date = min_value_date

    @property
    def max_value_date(self):
        """Gets the max_value_date of this FDMAPIDTOV1CurveValuesSummary.  # noqa: E501


        :return: The max_value_date of this FDMAPIDTOV1CurveValuesSummary.  # noqa: E501
        :rtype: datetime
        """
        return self._max_value_date

    @max_value_date.setter
    def max_value_date(self, max_value_date):
        """Sets the max_value_date of this FDMAPIDTOV1CurveValuesSummary.


        :param max_value_date: The max_value_date of this FDMAPIDTOV1CurveValuesSummary.  # noqa: E501
        :type: datetime
        """

        self._max_value_date = max_value_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FDMAPIDTOV1CurveValuesSummary, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FDMAPIDTOV1CurveValuesSummary):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
