# coding: utf-8

"""
    FDM API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class FDMAPIDTOV1CurveScenarioForecastValue(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'scenario_id': 'int',
        'forecast_date': 'datetime',
        'value_date': 'datetime',
        'value': 'float'
    }

    attribute_map = {
        'scenario_id': 'scenarioID',
        'forecast_date': 'forecastDate',
        'value_date': 'valueDate',
        'value': 'value'
    }

    def __init__(self, scenario_id=None, forecast_date=None, value_date=None, value=None):  # noqa: E501
        """FDMAPIDTOV1CurveScenarioForecastValue - a model defined in Swagger"""  # noqa: E501
        self._scenario_id = None
        self._forecast_date = None
        self._value_date = None
        self._value = None
        self.discriminator = None
        if scenario_id is not None:
            self.scenario_id = scenario_id
        if forecast_date is not None:
            self.forecast_date = forecast_date
        if value_date is not None:
            self.value_date = value_date
        if value is not None:
            self.value = value

    @property
    def scenario_id(self):
        """Gets the scenario_id of this FDMAPIDTOV1CurveScenarioForecastValue.  # noqa: E501


        :return: The scenario_id of this FDMAPIDTOV1CurveScenarioForecastValue.  # noqa: E501
        :rtype: int
        """
        return self._scenario_id

    @scenario_id.setter
    def scenario_id(self, scenario_id):
        """Sets the scenario_id of this FDMAPIDTOV1CurveScenarioForecastValue.


        :param scenario_id: The scenario_id of this FDMAPIDTOV1CurveScenarioForecastValue.  # noqa: E501
        :type: int
        """

        self._scenario_id = scenario_id

    @property
    def forecast_date(self):
        """Gets the forecast_date of this FDMAPIDTOV1CurveScenarioForecastValue.  # noqa: E501


        :return: The forecast_date of this FDMAPIDTOV1CurveScenarioForecastValue.  # noqa: E501
        :rtype: datetime
        """
        return self._forecast_date

    @forecast_date.setter
    def forecast_date(self, forecast_date):
        """Sets the forecast_date of this FDMAPIDTOV1CurveScenarioForecastValue.


        :param forecast_date: The forecast_date of this FDMAPIDTOV1CurveScenarioForecastValue.  # noqa: E501
        :type: datetime
        """

        self._forecast_date = forecast_date

    @property
    def value_date(self):
        """Gets the value_date of this FDMAPIDTOV1CurveScenarioForecastValue.  # noqa: E501


        :return: The value_date of this FDMAPIDTOV1CurveScenarioForecastValue.  # noqa: E501
        :rtype: datetime
        """
        return self._value_date

    @value_date.setter
    def value_date(self, value_date):
        """Sets the value_date of this FDMAPIDTOV1CurveScenarioForecastValue.


        :param value_date: The value_date of this FDMAPIDTOV1CurveScenarioForecastValue.  # noqa: E501
        :type: datetime
        """

        self._value_date = value_date

    @property
    def value(self):
        """Gets the value of this FDMAPIDTOV1CurveScenarioForecastValue.  # noqa: E501


        :return: The value of this FDMAPIDTOV1CurveScenarioForecastValue.  # noqa: E501
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this FDMAPIDTOV1CurveScenarioForecastValue.


        :param value: The value of this FDMAPIDTOV1CurveScenarioForecastValue.  # noqa: E501
        :type: float
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FDMAPIDTOV1CurveScenarioForecastValue, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FDMAPIDTOV1CurveScenarioForecastValue):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
