# coding: utf-8

"""
    FDM API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class CurveValuesApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def v1_curve_values_aggregated_curve_id_result_period_type_result_period_length_get(self, curve_id, result_period_type, result_period_length, **kwargs):  # noqa: E501
        """v1_curve_values_aggregated_curve_id_result_period_type_result_period_length_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v1_curve_values_aggregated_curve_id_result_period_type_result_period_length_get(curve_id, result_period_type, result_period_length, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int curve_id: (required)
        :param str result_period_type: (required)
        :param int result_period_length: (required)
        :param int scenario_id:
        :param datetime max_forecast_date:
        :param str result_timezone:
        :param datetime min_value_date:
        :param datetime max_value_date:
        :param bool calculate_proportional:
        :param bool exclude_nulls:
        :param bool source_is_quantity:
        :param str source_timezone:
        :param str source_period_type:
        :param int source_period_length:
        :param bool flatten:
        :return: list[FDMAPIDTOV1CurveAggregatedValue]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.v1_curve_values_aggregated_curve_id_result_period_type_result_period_length_get_with_http_info(curve_id, result_period_type, result_period_length, **kwargs)  # noqa: E501
        else:
            (data) = self.v1_curve_values_aggregated_curve_id_result_period_type_result_period_length_get_with_http_info(curve_id, result_period_type, result_period_length, **kwargs)  # noqa: E501
            return data

    def v1_curve_values_aggregated_curve_id_result_period_type_result_period_length_get_with_http_info(self, curve_id, result_period_type, result_period_length, **kwargs):  # noqa: E501
        """v1_curve_values_aggregated_curve_id_result_period_type_result_period_length_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v1_curve_values_aggregated_curve_id_result_period_type_result_period_length_get_with_http_info(curve_id, result_period_type, result_period_length, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int curve_id: (required)
        :param str result_period_type: (required)
        :param int result_period_length: (required)
        :param int scenario_id:
        :param datetime max_forecast_date:
        :param str result_timezone:
        :param datetime min_value_date:
        :param datetime max_value_date:
        :param bool calculate_proportional:
        :param bool exclude_nulls:
        :param bool source_is_quantity:
        :param str source_timezone:
        :param str source_period_type:
        :param int source_period_length:
        :param bool flatten:
        :return: list[FDMAPIDTOV1CurveAggregatedValue]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['curve_id', 'result_period_type', 'result_period_length', 'scenario_id', 'max_forecast_date', 'result_timezone', 'min_value_date', 'max_value_date', 'calculate_proportional', 'exclude_nulls', 'source_is_quantity', 'source_timezone', 'source_period_type', 'source_period_length', 'flatten']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v1_curve_values_aggregated_curve_id_result_period_type_result_period_length_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'curve_id' is set
        if ('curve_id' not in params or
                params['curve_id'] is None):
            raise ValueError("Missing the required parameter `curve_id` when calling `v1_curve_values_aggregated_curve_id_result_period_type_result_period_length_get`")  # noqa: E501
        # verify the required parameter 'result_period_type' is set
        if ('result_period_type' not in params or
                params['result_period_type'] is None):
            raise ValueError("Missing the required parameter `result_period_type` when calling `v1_curve_values_aggregated_curve_id_result_period_type_result_period_length_get`")  # noqa: E501
        # verify the required parameter 'result_period_length' is set
        if ('result_period_length' not in params or
                params['result_period_length'] is None):
            raise ValueError("Missing the required parameter `result_period_length` when calling `v1_curve_values_aggregated_curve_id_result_period_type_result_period_length_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'curve_id' in params:
            path_params['CurveID'] = params['curve_id']  # noqa: E501
        if 'result_period_type' in params:
            path_params['ResultPeriodType'] = params['result_period_type']  # noqa: E501
        if 'result_period_length' in params:
            path_params['ResultPeriodLength'] = params['result_period_length']  # noqa: E501

        query_params = []
        if 'scenario_id' in params:
            query_params.append(('ScenarioID', params['scenario_id']))  # noqa: E501
        if 'max_forecast_date' in params:
            query_params.append(('MaxForecastDate', params['max_forecast_date']))  # noqa: E501
        if 'result_timezone' in params:
            query_params.append(('ResultTimezone', params['result_timezone']))  # noqa: E501
        if 'min_value_date' in params:
            query_params.append(('MinValueDate', params['min_value_date']))  # noqa: E501
        if 'max_value_date' in params:
            query_params.append(('MaxValueDate', params['max_value_date']))  # noqa: E501
        if 'calculate_proportional' in params:
            query_params.append(('CalculateProportional', params['calculate_proportional']))  # noqa: E501
        if 'exclude_nulls' in params:
            query_params.append(('ExcludeNulls', params['exclude_nulls']))  # noqa: E501
        if 'source_is_quantity' in params:
            query_params.append(('SourceIsQuantity', params['source_is_quantity']))  # noqa: E501
        if 'source_timezone' in params:
            query_params.append(('SourceTimezone', params['source_timezone']))  # noqa: E501
        if 'source_period_type' in params:
            query_params.append(('SourcePeriodType', params['source_period_type']))  # noqa: E501
        if 'source_period_length' in params:
            query_params.append(('SourcePeriodLength', params['source_period_length']))  # noqa: E501
        if 'flatten' in params:
            query_params.append(('Flatten', params['flatten']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json', 'application/xml', 'text/xml', 'text/csv'])  # noqa: E501

        # Authentication setting
        auth_settings = ['apikey-v1']  # noqa: E501

        return self.api_client.call_api(
            '/v1/CurveValues/Aggregated/{CurveID}/{ResultPeriodType}/{ResultPeriodLength}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[FDMAPIDTOV1CurveAggregatedValue]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def v1_curve_values_curve_id_get(self, curve_id, **kwargs):  # noqa: E501
        """v1_curve_values_curve_id_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v1_curve_values_curve_id_get(curve_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int curve_id: (required)
        :param int scenario_id:
        :param datetime min_forecast_date:
        :param datetime max_forecast_date:
        :param datetime min_value_date:
        :param datetime max_value_date:
        :param str result_timezone:
        :return: list[FDMAPIDTOV1CurveScenarioForecastValue]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.v1_curve_values_curve_id_get_with_http_info(curve_id, **kwargs)  # noqa: E501
        else:
            (data) = self.v1_curve_values_curve_id_get_with_http_info(curve_id, **kwargs)  # noqa: E501
            return data

    def v1_curve_values_curve_id_get_with_http_info(self, curve_id, **kwargs):  # noqa: E501
        """v1_curve_values_curve_id_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v1_curve_values_curve_id_get_with_http_info(curve_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int curve_id: (required)
        :param int scenario_id:
        :param datetime min_forecast_date:
        :param datetime max_forecast_date:
        :param datetime min_value_date:
        :param datetime max_value_date:
        :param str result_timezone:
        :return: list[FDMAPIDTOV1CurveScenarioForecastValue]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['curve_id', 'scenario_id', 'min_forecast_date', 'max_forecast_date', 'min_value_date', 'max_value_date', 'result_timezone']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v1_curve_values_curve_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'curve_id' is set
        if ('curve_id' not in params or
                params['curve_id'] is None):
            raise ValueError("Missing the required parameter `curve_id` when calling `v1_curve_values_curve_id_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'curve_id' in params:
            path_params['CurveID'] = params['curve_id']  # noqa: E501

        query_params = []
        if 'scenario_id' in params:
            query_params.append(('ScenarioID', params['scenario_id']))  # noqa: E501
        if 'min_forecast_date' in params:
            query_params.append(('MinForecastDate', params['min_forecast_date']))  # noqa: E501
        if 'max_forecast_date' in params:
            query_params.append(('MaxForecastDate', params['max_forecast_date']))  # noqa: E501
        if 'min_value_date' in params:
            query_params.append(('MinValueDate', params['min_value_date']))  # noqa: E501
        if 'max_value_date' in params:
            query_params.append(('MaxValueDate', params['max_value_date']))  # noqa: E501
        if 'result_timezone' in params:
            query_params.append(('ResultTimezone', params['result_timezone']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json', 'application/xml', 'text/xml', 'text/csv'])  # noqa: E501

        # Authentication setting
        auth_settings = ['apikey-v1']  # noqa: E501

        return self.api_client.call_api(
            '/v1/CurveValues/{CurveID}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[FDMAPIDTOV1CurveScenarioForecastValue]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def v1_curve_values_forecast_curve_id_scenario_id_forecast_date_get(self, curve_id, scenario_id, forecast_date, **kwargs):  # noqa: E501
        """v1_curve_values_forecast_curve_id_scenario_id_forecast_date_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v1_curve_values_forecast_curve_id_scenario_id_forecast_date_get(curve_id, scenario_id, forecast_date, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int curve_id: (required)
        :param int scenario_id: (required)
        :param datetime forecast_date: (required)
        :param datetime min_value_date:
        :param datetime max_value_date:
        :param str result_timezone:
        :return: list[FDMAPIDTOV1CurveValue]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.v1_curve_values_forecast_curve_id_scenario_id_forecast_date_get_with_http_info(curve_id, scenario_id, forecast_date, **kwargs)  # noqa: E501
        else:
            (data) = self.v1_curve_values_forecast_curve_id_scenario_id_forecast_date_get_with_http_info(curve_id, scenario_id, forecast_date, **kwargs)  # noqa: E501
            return data

    def v1_curve_values_forecast_curve_id_scenario_id_forecast_date_get_with_http_info(self, curve_id, scenario_id, forecast_date, **kwargs):  # noqa: E501
        """v1_curve_values_forecast_curve_id_scenario_id_forecast_date_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v1_curve_values_forecast_curve_id_scenario_id_forecast_date_get_with_http_info(curve_id, scenario_id, forecast_date, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int curve_id: (required)
        :param int scenario_id: (required)
        :param datetime forecast_date: (required)
        :param datetime min_value_date:
        :param datetime max_value_date:
        :param str result_timezone:
        :return: list[FDMAPIDTOV1CurveValue]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['curve_id', 'scenario_id', 'forecast_date', 'min_value_date', 'max_value_date', 'result_timezone']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v1_curve_values_forecast_curve_id_scenario_id_forecast_date_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'curve_id' is set
        if ('curve_id' not in params or
                params['curve_id'] is None):
            raise ValueError("Missing the required parameter `curve_id` when calling `v1_curve_values_forecast_curve_id_scenario_id_forecast_date_get`")  # noqa: E501
        # verify the required parameter 'scenario_id' is set
        if ('scenario_id' not in params or
                params['scenario_id'] is None):
            raise ValueError("Missing the required parameter `scenario_id` when calling `v1_curve_values_forecast_curve_id_scenario_id_forecast_date_get`")  # noqa: E501
        # verify the required parameter 'forecast_date' is set
        if ('forecast_date' not in params or
                params['forecast_date'] is None):
            raise ValueError("Missing the required parameter `forecast_date` when calling `v1_curve_values_forecast_curve_id_scenario_id_forecast_date_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'curve_id' in params:
            path_params['CurveID'] = params['curve_id']  # noqa: E501
        if 'scenario_id' in params:
            path_params['ScenarioID'] = params['scenario_id']  # noqa: E501
        if 'forecast_date' in params:
            path_params['ForecastDate'] = params['forecast_date']  # noqa: E501

        query_params = []
        if 'min_value_date' in params:
            query_params.append(('MinValueDate', params['min_value_date']))  # noqa: E501
        if 'max_value_date' in params:
            query_params.append(('MaxValueDate', params['max_value_date']))  # noqa: E501
        if 'result_timezone' in params:
            query_params.append(('ResultTimezone', params['result_timezone']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json', 'application/xml', 'text/xml', 'text/csv'])  # noqa: E501

        # Authentication setting
        auth_settings = ['apikey-v1']  # noqa: E501

        return self.api_client.call_api(
            '/v1/CurveValues/Forecast/{CurveID}/{ScenarioID}/{ForecastDate}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[FDMAPIDTOV1CurveValue]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def v1_curve_values_latest_forecast_curve_id_scenario_id_get(self, curve_id, scenario_id, **kwargs):  # noqa: E501
        """v1_curve_values_latest_forecast_curve_id_scenario_id_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v1_curve_values_latest_forecast_curve_id_scenario_id_get(curve_id, scenario_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int curve_id: (required)
        :param int scenario_id: (required)
        :param datetime as_at_date:
        :param datetime min_value_date:
        :param datetime max_value_date:
        :param str result_timezone:
        :return: list[FDMAPIDTOV1CurveValue]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.v1_curve_values_latest_forecast_curve_id_scenario_id_get_with_http_info(curve_id, scenario_id, **kwargs)  # noqa: E501
        else:
            (data) = self.v1_curve_values_latest_forecast_curve_id_scenario_id_get_with_http_info(curve_id, scenario_id, **kwargs)  # noqa: E501
            return data

    def v1_curve_values_latest_forecast_curve_id_scenario_id_get_with_http_info(self, curve_id, scenario_id, **kwargs):  # noqa: E501
        """v1_curve_values_latest_forecast_curve_id_scenario_id_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v1_curve_values_latest_forecast_curve_id_scenario_id_get_with_http_info(curve_id, scenario_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int curve_id: (required)
        :param int scenario_id: (required)
        :param datetime as_at_date:
        :param datetime min_value_date:
        :param datetime max_value_date:
        :param str result_timezone:
        :return: list[FDMAPIDTOV1CurveValue]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['curve_id', 'scenario_id', 'as_at_date', 'min_value_date', 'max_value_date', 'result_timezone']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v1_curve_values_latest_forecast_curve_id_scenario_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'curve_id' is set
        if ('curve_id' not in params or
                params['curve_id'] is None):
            raise ValueError("Missing the required parameter `curve_id` when calling `v1_curve_values_latest_forecast_curve_id_scenario_id_get`")  # noqa: E501
        # verify the required parameter 'scenario_id' is set
        if ('scenario_id' not in params or
                params['scenario_id'] is None):
            raise ValueError("Missing the required parameter `scenario_id` when calling `v1_curve_values_latest_forecast_curve_id_scenario_id_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'curve_id' in params:
            path_params['CurveID'] = params['curve_id']  # noqa: E501
        if 'scenario_id' in params:
            path_params['ScenarioID'] = params['scenario_id']  # noqa: E501

        query_params = []
        if 'as_at_date' in params:
            query_params.append(('AsAtDate', params['as_at_date']))  # noqa: E501
        if 'min_value_date' in params:
            query_params.append(('MinValueDate', params['min_value_date']))  # noqa: E501
        if 'max_value_date' in params:
            query_params.append(('MaxValueDate', params['max_value_date']))  # noqa: E501
        if 'result_timezone' in params:
            query_params.append(('ResultTimezone', params['result_timezone']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json', 'application/xml', 'text/xml', 'text/csv'])  # noqa: E501

        # Authentication setting
        auth_settings = ['apikey-v1']  # noqa: E501

        return self.api_client.call_api(
            '/v1/CurveValues/LatestForecast/{CurveID}/{ScenarioID}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[FDMAPIDTOV1CurveValue]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
